In [1]:
import numpy as np
import random
Q=np.zeros([6,6])
Q

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [2]:
na=-np.Inf
R=np.array([[na,na,na,na,0,na],
            [na,na,na,0,na,100],
            [na,na,na,0,na,na],
            [na,0,0,na,0,na],
            [0,na,na,0,na,100],
            [na,0,na,na,0,100]])
R

array([[-inf, -inf, -inf, -inf,   0., -inf],
       [-inf, -inf, -inf,   0., -inf, 100.],
       [-inf, -inf, -inf,   0., -inf, -inf],
       [-inf,   0.,   0., -inf,   0., -inf],
       [  0., -inf, -inf,   0., -inf, 100.],
       [-inf,   0., -inf, -inf,   0., 100.]])

In [3]:
class Qlearning:
    def __init__(self,gamma,shape,R,episode,goal):
        self.gamma=gamma
        self.shape=shape
        self.Q=np.zeros((self.shape[0],self.shape[1]))
        self.R=R
        self.episode=episode
        self.goal=goal
    def rule(self,state,action,gamma):
        all_actions=list(np.where(self.R[action,:]!=-np.Inf)[0])#get all possible actions from next state
        state2AllAction=[]
        for i in all_actions:
            state2AllAction.append(self.Q[action,i])
        self.Q[state,action]=self.R[state,action]+self.gamma*(max(state2AllAction)) 
        #Q[state,action]=R[state,action]+gmmma*max(values of all possible actions)
        return action
    def training(self):
        #set a limit
        for time in range(self.episode):
            initial=random.randint(0,self.shape[0]-1)#randome initial
            option=True
            while option:
                if initial==self.goal:
                    option=False#if we finding the goal ,finish it.
                action=random.choice(list(np.where(self.R[initial,:]!=-np.Inf)[0]))#random choose one amnong from all possible actions
                next_state=self.rule(initial,action,self.gamma)
                initial=next_state

In [4]:
tmp=Qlearning(0.8,[6,6],R,700,5)
tmp.training()

In [5]:
tmp.Q
#follow by the website : https://people.revoledu.com/kardi/tutorial/ReinforcementLearning/Q-Learning-Algorithm.htm

array([[  0.,   0.,   0.,   0., 400.,   0.],
       [  0.,   0.,   0., 320.,   0., 500.],
       [  0.,   0.,   0., 320.,   0.,   0.],
       [  0., 400., 256.,   0., 400.,   0.],
       [320.,   0.,   0., 320.,   0., 500.],
       [  0., 400.,   0.,   0., 400., 500.]])